export const // eslint-disable-line one-var
    SET_AUTHENTICATED = 'SET_AUTHENTICATED',
    SET_CATEGORIES = 'SET_CATEGORIES',
    SET_MAIN_SLIDES = 'SET_MAIN_SLIDES',
    SET_PRODUCTS = 'SET_PRODUCTS',
    SET_FILTERED_PRODUCTS = 'SET_FILTERED_PRODUCTS',
    SET_ORDERS = 'SET_ORDERS',
    SET_COMMENTS = 'SET_COMMENTS',
    SET_FILTERED_ORDERS = 'SET_FILTERED_ORDERS',
    SET_SEO = 'SET_SEO';
