export const // eslint-disable-line one-var
    SET_CATEGORIES = 'SET_CATEGORIES',
    SET_PRODUCTS_TO_MAP = 'SET_PRODUCTS_TO_MAP',
    SET_MAIN_SLIDES = 'SET_MAIN_SLIDES',
    SET_MEDIA_INFO = 'SET_MEDIA_INFO';
