export const // eslint-disable-line one-var
    OPEN_POPUP = 'OPEN_POPUP',
    CLOSE_POPUP = 'CLOSE_POPUP',
    SET_CATEGORIES = 'SET_CATEGORIES',
    SET_PRODUCTS_TO_MAP = 'SET_PRODUCTS_TO_MAP',
    SET_MAIN_SLIDES = 'SET_MAIN_SLIDES',
    SET_MEDIA_INFO = 'SET_MEDIA_INFO',
    OPEN_BASKET_POPUP = 'OPEN_BASKET_POPUP',
    CLOSE_BASKET_POPUP = 'CLOSE_BASKET_POPUP';
